return {
  "RINK", "RINK_WALK", "RINK_SHIELD", "RINK_HOLD", "RINK_ATTACK2", "RINK_ATTACK", "RINK_BOW", "RINK_WALK2",
  "XELDA", "XELDA_WALK", "XELDA_SHIELD", "XELDA_HOLD", "XELDA_ATTACK2", "XELDA_ATTACK", "XELDA_BOW", "XELDA_WALK2",
  "SLIME", "ESLIME", "PIG", "SKELETON", "BAT1", "BAT2", "BAT_SIT", "GHOST",
  "HASH", "LAMP", "GLOVE", "BOW", "CONTAINER", "KEY", "FISH", "FISH2",
  "BIGKEY", "BLOCK", "BOMB1", "BOMB2", "YELLOW", "CYAN", "MAGENTA", "?",
  "HEART_EMPTY", "HEART_HALF", "HEART", "RUBY1", "RUBY5", "RUBY10", "RUBY50", "RUBY100",
  "ARROWS", "SWORD", "ELECTRO", "SHOOTING", "DUMMY", "BOMB", "ARROW", "NUT",
  "?", "?", "?", "?", "?", "?", "?", "LOCK",
  "?", "?", "?", "?", "?", "?", "?", "HOLE",
  "?", "?", "SWITCH", "SWITCH2", "?", "?", "?", "CHEST",
  "?", "?", "?", "TABLET", "SHIELD", "?", "GRASS", "GRID",
  "?", "?", "TRIGGER", "TRIGGER2", "?", "?", "BIG_LOCK", "BIG_LOCK_OPEN",
  "?", "?", "EYE", "EYE2", "?", "?", "?", "?",
  "?", "?", "?", "?", "?", "?", "?", "?",
  "?", "?", "?", "LAMPPOST", "LAMPPOST_ON", "ICE_SLOPE_L", "ICE_SLOPE_R", "?",
  "CARPET", "RED_CHAIR", "BLUE_CHAIR", "TOP_LAMP", "LIGHT", "WOLF_DUCK_1", "WOLF_DUCK_2", "WOLF_HOWL",
  "CARPET_END", "TABLE", "WINDOW", "BED_L", "BED_R", "WOLF_RUN", "WOLF_JUMP", "WOLF",
  "BLACK", "FAIRY", "KING", "Z", "XELDA_WAIT", "PUFF", "CUT_GRASS", "FLY_GRASS",
  "SLEEPY_RINK", "SLEEPY_RINK_WALK", "SLEEPY_RINK_SHIELD", "SLEEPY_RINK_HOLD", "SLEEPY_RINK_ATTACK2", "SLEEPY_RINK_ATTACK", "SLEEPY_RINK_BOW", "SLEEPY_RINK_WALK2",
  "XELDA_BLINK", "SLEEPY_RINK_BLINK", "RINK_BLINK", "?", "?", "?", "LADDER",
}
